title: easynotes
email: your-email@example.com
description: >- 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed

markdown: kramdown

kramdown:
  input: GFM

baseurl: /easynotes
url: "https://pawar41.github.io/easynotes"

#--------------------------------------------------------------------------

logo: "Easy Notes"
shlogan: "NOTES for Last Minute."
